### ISSUE TITLE
mazecompositor doesn't compile on Kubuntu 12.04

### ISSUE THREAD

**Issue by overby-me** [capisce/mazecompositor#1]
I'm using this qt5 ppa: ppa:canonical-qt5-edgers/qt5-daily to compile mazecompositor on Kubuntu 12.04.

The following error output appears:
/opt/qt5/bin/qmake
make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_GUI_LIB -DQT_CORE_LIB -I/opt/qt5/mkspecs/linux-g++-64 -I. -I/opt/qt5/include -I/opt/qt5/include/QtCompositor -I/opt/qt5/include/QtGui -I/opt/qt5/include/QtCore -I. -o .obj/camera.o camera.cpp
camera.cpp: In member function ‘void Camera::updateMatrix() const’:
camera.cpp:142:41: error: invalid conversion from ‘float_’ to ‘int’ [-fpermissive]
/opt/qt5/include/QtGui/qmatrix4x4.h:204:14: error:   initializing argument 1 of ‘QMatrix4x4::QMatrix4x4(int)’ [-fpermissive]
/opt/qt5/include/QtGui/qmatrix4x4.h:204:14: error: ‘QMatrix4x4::QMatrix4x4(int)’ is private
camera.cpp:142:41: error: within this context
make: *_\* [.obj/camera.o] Error 1

Is this issue related to outdated libraries?

**Comment by capisce** [comment]
That's right, the API changed recently in Qt 5. I've pushed a new change to
make it build with both the old and the new API.

Alternatively, you can change "float data[] =" to be "double data[] =" for
now.
